name: CI/CD for Angular Project

on:
  push:
    branches:
      - main  # Cambia esto si tu rama principal tiene otro nombre

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Asegúrate de usar la versión de Node.js compatible con Angular

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test -- --watch=false

      - name: Build project
        run: npm run build -- --configuration=production

      # Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/plaxi-frontend  # Cambia 'plaxi-frontend' al nombre de tu aplicación en angular.json si es diferente
